name: Esegui script una volta

on:
  workflow_dispatch:  # permette di far partire il workflow manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run script
      run: python script.py
